package co.edu.unac.integrador1.login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import co.edu.unac.integrador1.votacion.Grupo;
import co.edu.unac.integrador1.votacion.Candidato;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;


/**
 *
 * @author Nicol Alejandra
 */
public class CrearGruposFrame extends javax.swing.JFrame {
        private DefaultListModel<Candidato> modeloCandidatos = new DefaultListModel<>();

    /**
     * Creates new form CrearGruposFrame
     */
    public CrearGruposFrame() {
        initComponents();
       // Crea un nuevo JList que acepte objetos de tipo Candidato
    javax.swing.JList<co.edu.unac.integrador1.votacion.Candidato> nuevaLista = new javax.swing.JList<>();
    // Usa el modelo que ya tienes (modeloCandidatos)
    nuevaLista.setModel(modeloCandidatos);
    // Reemplaza el JList original en el JScrollPane
    jScrollPane2.setViewportView(nuevaLista);
    // Asigna la nueva lista a jList2 (se realiza un cast, ya que jList2 fue declarado como JList<String>)
    jList2 = (javax.swing.JList) nuevaLista;
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreGrupo = new javax.swing.JTextField();
        btnAgregarCandidatoAlGrupo = new javax.swing.JButton();
        btnGuardarGrupo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreGrupo.setText("ingrese el nombre del grupo.");
        txtNombreGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGrupoActionPerformed(evt);
            }
        });

        btnAgregarCandidatoAlGrupo.setText("ingresar los datos de un candidato");
        btnAgregarCandidatoAlGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCandidatoAlGrupoActionPerformed(evt);
            }
        });

        btnGuardarGrupo.setText("Guardar Grupo");
        btnGuardarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGrupoActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnGuardarGrupo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarCandidatoAlGrupo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34))))
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarCandidatoAlGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarGrupo)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGrupoActionPerformed
 // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGrupoActionPerformed

    private void btnAgregarCandidatoAlGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCandidatoAlGrupoActionPerformed
        AgregarCandidatoFrame agregarFrame = new AgregarCandidatoFrame();
        agregarFrame.setVisible(true);

        // Supongamos que AgregarCandidatoFrame tiene un método público getCandidato() que devuelve el candidato creado
        Candidato nuevoCandidato = agregarFrame.getCandidato();
        if(nuevoCandidato != null){
            modeloCandidatos.addElement(nuevoCandidato);
        }
    }//GEN-LAST:event_btnAgregarCandidatoAlGrupoActionPerformed

    private void btnGuardarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGrupoActionPerformed
        String nombreGrupo = txtNombreGrupo.getText().trim();
        if(nombreGrupo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para el grupo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Grupo grupo = new Grupo(nombreGrupo);
        // Recorrer el modelo y agregar cada candidato al grupo
        for (int i = 0; i < modeloCandidatos.getSize(); i++) {
            grupo.agregarCandidato(modeloCandidatos.getElementAt(i));
        }

        // Aquí podrías guardar el grupo en una lista global, base de datos o mostrarlo
        JOptionPane.showMessageDialog(this, "Grupo guardado:\n" + grupo.toString(), "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Opcional: limpiar la interfaz
        txtNombreGrupo.setText("");
        modeloCandidatos.clear();// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearGruposFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearGruposFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearGruposFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearGruposFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearGruposFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCandidatoAlGrupo;
    private javax.swing.JButton btnGuardarGrupo;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNombreGrupo;
    // End of variables declaration//GEN-END:variables
}
